services:

  db:
    env_file:
      - .env
    image: postgres:15.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql

  keycurl:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - "${GO_PORT}:${GO_PORT}"
    depends_on:
      db:
        condition: service_healthy
